In [1]:
#####Basic Numpy Array 

In [2]:
###Create an empty numpy array###

In [8]:
import numpy as np

In [5]:
import numpy as np

#create empty array
empty_np_array = np.empty((3,3))
print(empty_np_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
###create full array
full_array = np.full((5,5),3)
print(full_array)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [13]:
###create numpy array with all ones
array = np.ones(3)
print(array)

###
array_with_shape = np.ones((3,4))
print(array_with_shape)


###array of ones with specific data type
array_ones = np.ones(6, dtype=int)
print(array_ones)

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1 1 1 1 1 1]


In [16]:
###multi-d array of ones
ones_array_3d = np.ones((3, 3, 4))
print(ones_array_3d)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [19]:
###Check whether a numpy array contains a specific row

arr = np.arange(1, 21).reshape(4, 5)

print([1,2,3,4,5] in arr.tolist())
print([21,22,23,24,25] in arr.tolist())

True
False


In [3]:
import numpy as np

In [5]:
arr01 = np.arange(1)
arr02 = np.arange(10).reshape(2,5)
print("1d array ",arr01)
print("2 d array",arr02)

1d array  [0]
2 d array [[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
for a,b in np.nditer([arr01,arr02]):
    print("%d:%d" % (a,b))

0:0
0:1
0:2
0:3
0:4
0:5
0:6
0:7
0:8
0:9


In [13]:
import numpy as np

an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 4], [3, 4]])

comparison = an_array == another_array
print(comparison)
equal_arrays = comparison.all()

print(equal_arrays)

[[ True False]
 [ True  True]]
False


In [17]:
a = [11,22,33]
b=[22,33,11]
print(np.greater(a, b))
print(np.greater_equal(a, b))
print(np.less(a,b))
print(np.less_equal(a,b))

[False False  True]
[False False  True]
[ True  True False]
[ True  True False]


In [19]:
if np.array_equal(a, b):
    print("Equal")
else:
    print("Not Equal")

Not Equal


In [7]:
import numpy as np
arr123=np.zeros((2,3))
##np.zeros(shape) , shape means array size
##np.zeros(1) -> for 1 d , np.zeros(3,3) -> for 2 d
print(arr123)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
arr12=np.ones(1)
print(arr12)

[1.]


In [10]:
## fill array with specific value

##full((shape),value)
full_func=np.full((2,3),5)
print(full_func)

[[5 5 5]
 [5 5 5]]
