In [1]:
import numpy as np

In [6]:
## creating sequence of numbers

### arange(start,stop,step)

seq1=np.arange(0,11)
print(seq1)

seq2=np.arange(1,11,2)
print(seq2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [7]:
### creating identity matrices

## identity matrix -> sq matrix with ones on diagonal and 0's elsewhere

###eye(size)
identity_matrix=np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


shapre,size and dim

In [13]:
create_array=np.arange(0,24).reshape(4,6)
print(create_array)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [16]:
print(create_array.size)
print(create_array.shape)
print(create_array.ndim)

24
(4, 6)
2
