In [1]:
#####Basic Numpy Array 

In [2]:
###Create an empty numpy array###

In [5]:
import numpy as np

#create empty array
empty_np_array = np.empty((3,3))
print(empty_np_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
###create full array
full_array = np.full((5,5),3)
print(full_array)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [13]:
###create numpy array with all ones
array = np.ones(3)
print(array)

###
array_with_shape = np.ones((3,4))
print(array_with_shape)


###array of ones with specific data type
array_ones = np.ones(6, dtype=int)
print(array_ones)

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1 1 1 1 1 1]


In [16]:
###multi-d array of ones
ones_array_3d = np.ones((3, 3, 4))
print(ones_array_3d)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
