IMPORT NUMPY PACKAGE UNDER THE NAME NP

In [2]:
import numpy as np;

DISPLAY NUMPY VERSION

In [2]:
print(np.__version__)

2.3.2


TO SHOW CONFIG

In [4]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-tmvlc1e1/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-tmvlc1e1/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-tmvlc1e1/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-tmvlc1e1/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  US

In [6]:
# np.empty(10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create a null vector of size 10 with 5th value as 1

In [12]:
new_array=np.zeros(10)
new_array[4]=1
print(new_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with value from range 10 to 49

In [13]:
arr1=np.arange(10,50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Create a vector list in reverse order 

In [17]:
print(arr1[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [19]:
three_three=np.arange(0,9).reshape(3,3)
print(three_three)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Find indices of non zero element in [1,2,0,0,4,0]

In [24]:
lst=[1,2,0,0,4,0]
arr=np.array(lst)
indices=np.where(arr!=0)
print(indices[0])

[0 1 4]


Create a 3x3 identity matrix

In [5]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 3x3x3 matrix with random values

In [7]:
print(np.random.random((3,3,3)))

[[[0.15814371 0.34144821 0.29373222]
  [0.79328235 0.09124735 0.60958875]
  [0.72898154 0.68343667 0.51522152]]

 [[0.19662858 0.31239049 0.09284011]
  [0.53060152 0.38473483 0.30184396]
  [0.81375627 0.62693417 0.53683428]]

 [[0.79485225 0.55158614 0.36968761]
  [0.54526913 0.50174275 0.74953379]
  [0.25709156 0.2159669  0.17253633]]]


Create a 10 x 10 array with random value and find max and min

In [13]:
maxii=np.random.randint(1,51,(10,10)).max()
minii=np.random.randint(1,51,(10,10)).min()
print(maxii)
print(minii)

49
1


Create a random vector of size 30 and find mean

In [14]:
print(np.random.randint(1,51,(30)).mean())

24.5


Create a 2d array with 1 on the border and 0 inside

In [17]:
z1=np.ones((10,10))
z1[1:-1,1:-1]=0
z1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])