### Indexing and Slicing

In [1]:
import numpy as np

In [2]:
arr=np.arange(1,11)

In [7]:
print(arr[1])
print(arr[1:9:2])

2
[2 4 6 8]


In [15]:
arr2d=np.arange(0,10).reshape(2,5)
print(arr2d[0:,1:3])

[[1 2]
 [6 7]]


##### Fancy Indexing


- selecting multiple elements at once
- useful in selecting non-sequential values
- you have to pass it as a list
- it creates a copy of your data does not modify original array

In [20]:
print(arr[[0,4,5]])

[1 5 6]


## Boolean Masking : filtering data based on condition

In [21]:
print(arr[arr>3])

[ 4  5  6  7  8  9 10]


In [22]:
print(arr[arr>13])

[]


##### Flattening

- ravel() -> returns a view original array is modified
- flatten() ->copy of the original array 

- used when you want to convert multi-d array into 1-d array

In [24]:
arrd=arr2d.ravel()
print(arrd)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
arr_d=arr2d.flatten()
print(arr_d)

[0 1 2 3 4 5 6 7 8 9]
