## Creating np array using zeros

In [1]:
import numpy as np

In [3]:
## 1 d array using all zeros
np_1d=np.zeros(1)
print(np_1d)

[0.]


In [5]:
## 2 d array using all zeros
np_2d=np.zeros((2,3),dtype=int)
print(np_2d)

[[0 0 0]
 [0 0 0]]


## Creating np array using ones

In [6]:
np_ones_1d = np.ones(5)
print(np_ones_1d)

[1. 1. 1. 1. 1.]


In [7]:
###2d array using ones
np_ones_2d= np.ones((3,3),dtype=int)
print(np_ones_2d)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
