## Matrix Related problems

In [1]:
import numpy as np

In [2]:
gfg=np.matrix('[1,2,3;4,5,6;7,8,9]')
print(gfg)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(gfg.max())

9


In [4]:
print(gfg.min())

1


In [7]:
print(np.shape(gfg))

(3, 3)


Syntax : matrix.take(index, axis)
Return : Return matrix of selected indexes

In [8]:
print(gfg.take(2))

[[3]]


In [10]:
print(gfg.take(0,1))
##row =0 column = 1

[[1 4 7]]


In [11]:
print(gfg.sum())

45
